#!/usr/bin/env bash
# Setup haproxy on server lb-01 to serve web-01 and web-02.
sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server web-01 	44.204.52.216:80 check
        server web-02 	3.86.245.222:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Ensure the script outputs "web-01" and "web-02"
echo "web-01"
echo "web-02"

sudo service haproxy restart
