#!/usr/bin/env bash
# This script transfers a file to a remote server using SCP
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

if [ "$?" -eq 0 ]; then
    echo "File successfully transferred to $USERNAME@$SERVER_IP:~/"
else
    echo "Error transferring file."
    exit 1
fi