#!/usr/bin/env bash

# Debugging output
echo "Arguments: $1 $2 $3 $4"

# Check if the correct number of arguments are passed
declare -i ARGS="$#"
if [ "$ARGS" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    # Debug: Print the SCP command being run
    echo "Running SCP command: scp -v -i \"$4\" -o StrictHostKeyChecking=no \"$1\" \"$3@$2:~/\""
    
    # Run the SCP command
    scp -v -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi