#!/usr/bin/env bash
# Sets up nginx

sudo apt-get update -y
sudo apt-get install -y nginx

# Ensure nginx is running without using systemctl
sudo nginx

# Write the expected content to the index.html file
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Reload Nginx without using systemctl or service
sudo nginx -s reload