#!/usr/bin/env bash
# Configure Nginx for a 301 redirect

# Install Nginx if not already installed
apt-get update -y
apt-get install -y nginx

# Create a basic HTML page with the required content
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure the redirection by adding a location block to the default config
redirect_config="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "/server_name _;/a $redirect_config" /etc/nginx/sites-available/default
# sed -i "/server_name _;/a \\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-available/default

# Restart Nginx to a`pply changes
service nginx restart
