#!/usr/bin/env bash
# Sets up 404

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	error_page 404 /404.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
        }
	location /redirect_me {
                return 301 https://github.com/J0SHUALU;
        }
}
"
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "$config" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart